### ISSUE TITLE
creating a cluster with barman-cloud-plugin got stuck

### ISSUE THREAD

**Issue by smiyc** [cloudnative-pg/cnpg-playground#16]
I set up a new cpng-playground environment to test the barman plugin.
When I create a cluster, It got stuck at: 

```
   Type    Reason                       Age   From            Message                                                                                        │
   ----    ------                       ----  ----            -------                                                                                        │
   Normal  CreatingPodDisruptionBudget  26m   cloudnative-pg  Creating PodDisruptionBudget pg-eu-primary                                                     
   Normal  CreatingPodDisruptionBudget  26m   cloudnative-pg  Creating PodDisruptionBudget pg-eu                                                             │
   Normal  CreatingServiceAccount       26m   cloudnative-pg  Creating ServiceAccount                                                                        │
   Normal  CreatingRole                 26m   cloudnative-pg  Creating Cluster Role     
```

         

The cluster gets created when I comment out all plugin related from the cluster.yaml

This is how I set up the environment:
```
## EU
# cnpg manager
kubectl cnpg install generate --control-plane | kubectl --context kind-k8s-eu apply -f - --server-side
kubectl --context kind-k8s-eu rollout status deployment -n cnpg-system cnpg-controller-manager

# cert manager
kubectl --context kind-k8s-eu apply -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
kubectl --context kind-k8s-eu rollout status deployment -n cert-manager cert-manager
kubectl --context kind-k8s-eu rollout status deployment -n cert-manager cert-manager-cainjector
kubectl --context kind-k8s-eu rollout status deployment -n cert-manager cert-manager-webhook

# barman plugin
kubectl --context kind-k8s-eu apply -f https://raw.githubusercontent.com/cloudnative-pg/plugin-barman-cloud/refs/heads/main/manifest.yaml
kubectl --context kind-k8s-eu rollout status deployment -n cnpg-system barman-cloud


# pg cluster
kubectl --context kind-k8s-eu apply -f ./examples/object-stores/minio-eu.yaml  
kubectl --context kind-k8s-eu apply -f ./examples/eu/pg-eu.yaml
kubectl cnpg status pg-eu --context=kind-k8s-eu
```

I also tried the v16.2 cert-manager as described in the readme, but the error is the same.

Find the cluster / operator report attached[overview.txt](https://github.com/user-attachments/files/18269239/overview.txt)
[report_cluster_pg-eu_2024-12-29T10:33:07Z.zip](https://github.com/user-attachments/files/18269240/report_cluster_pg-eu_2024-12-29T10.33.07Z.zip)
[report_operator_2024-12-29T10:33:24Z.zip](https://github.com/user-attachments/files/18269241/report_operator_2024-12-29T10.33.24Z.zip)

**Comment by gbartolini** [comment]
Can you try again with the new README instructions (which point to the latest release of the plugin)?

Also, remember that the object stores must be defined in both clusters, not just in the local one, for cross-region communication of object stores.

**Comment by gbartolini** [comment]
You also need to ensure the API for cert-manager is ready before creating the plugin deployment, for example:

```
cmctl check api --wait=2m --context kind-k8s-eu
```

**Comment by gbartolini** [comment]
Please try with PR #19 as well.

**Comment by smiyc** [comment]
> Can you try again with the new README instructions (which point to the latest release of the plugin)in PR [#17](https://github.com/cloudnative-pg/cnpg-playground/pull/17) ?
> 
> Also, remember that the object stores must be defined in both clusters, not just in the local one, for cross-region communication of object stores.

with the new readme the setup it's working!

one thing, imo cmctl should be mentioned in [prerequisites](https://github.com/cloudnative-pg/cnpg-playground?tab=readme-ov-file#prerequisites) or  [additional-tools](https://github.com/cloudnative-pg/cnpg-playground?tab=readme-ov-file#additional-tools)

...I just saw that wit [PR#19](https://github.com/cloudnative-pg/cnpg-playground/pull/19) the cmctl prerequisits are mentioned there
